eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${server.port:8080}
  client:
    serviceUrl:
      defaultZone: ${service-registry.uri:http://127.0.0.1:8761}/eureka/
