server:
  port: ${PORT:8101}

spring:
  data:
    mongodb:
      host: ${mongoserver:localhost}
      port: 27017

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eurekasvc:192.168.99.100}:8761/eureka/
